# Generated by Django 4.2.4 on 2023-08-20 12:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worlds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True)),
                ('world', models.CharField(max_length=200)),
                ('translation', models.TextField(blank=True, null=True)),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='info')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
