# Generated by Django 4.2.4 on 2023-08-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worlds',
            options={'ordering': ['-pk', 'world']},
        ),
        migrations.AddField(
            model_name='worlds',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
