# Generated by Django 4.2.4 on 2023-08-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_worlds_options_worlds_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worlds',
            name='data',
        ),
    ]
